### ISSUE TITLE
Include MIDI only controls?

### ISSUE THREAD

**Issue by waterjump** [rolodato/volca-keys-editor#6]
Volca keys has a control change called Expression that can only be change via MIDI.  Include this in the patch editor?  See http://media.aadl.org/files/catalog_guides/1444140_chart.pdf for reference.

**Comment by rolodato** [comment]
I saw this in the MIDI chart but don't know what it's even for :) Does it actually do anything?

**Comment by waterjump** [comment]
Can't find any video demonstrations online.  I imagine it does something.  Only one way to find out.

**Comment by waterjump** [comment]
According to [this guy](http://www.mpc-forums.com/viewtopic.php?f=11&t=165004&start=180#p1633984), it controls VCA, so pretty much volume.  I don't think it's useful for static patches.  Worth considering if you implement MIDI to browser to Volca in realtime though.

**Comment by rolodato** [comment]
Let me try it out to confirm. If it's just volume, I agree that it doesn't make sense for an editor. If it can be motion sequenced (highly doubt it) it would be useful to have though.

**Comment by rolodato** [comment]
Just tested it out, it's a non-automatable volume control. As the name implies, it's meant for expression pedals for performance control of volume. Oddly enough, you can't even change the volume while a note is playing, so it doesn't even behave like a proper volume pedal. The new volume is played after a retrigger.
